namespace Mcp.Palma;

/// <summary>
/// Configuration for the Palma → MCP remote pipeline (separate-process scenario).
/// Bound from appsettings.json under "PalmaMcpRemote".
///
/// Authentication uses the OAuth2 client credentials flow:
///   1. MCP server obtains a bearer token from the identity provider.
///   2. All API calls carry  Authorization: Bearer {token}  and  AuthScheme: {SchemeId}.
/// </summary>
public sealed class PalmaRemoteMcpOptions
{
    /// <summary>
    /// Base URL of the remote Palma web API.
    /// Example: "https://eu.palmacloud.com"
    /// </summary>
    public required string ApiBaseUrl { get; init; }

    /// <summary>
    /// AuthScheme identifier sent on every request (as the <c>AuthScheme</c> header).
    /// Identifies which IDP / authentication scheme Palma should use to validate the token.
    /// </summary>
    public required string SchemeId { get; init; }

    // ── OAuth2 client credentials ─────────────────────────────────────────────

    /// <summary>
    /// Token endpoint URL of the identity provider.
    /// Azure AD: "https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token"
    /// Keycloak : "https://{host}/realms/{realm}/protocol/openid-connect/token"
    /// </summary>
    public required string TokenEndpoint { get; init; }

    /// <summary>Client application ID registered with the identity provider.</summary>
    public required string ClientId { get; init; }

    /// <summary>Client secret generated by the identity provider. Keep this in a secret store.</summary>
    public required string ClientSecret { get; init; }

    /// <summary>
    /// OAuth2 scope to request.
    /// Azure AD : "https://{region}.palmacloud.com/.default"
    /// Keycloak : "palma-api"
    /// </summary>
    public required string Scope { get; init; }

    // ── Tool discovery ────────────────────────────────────────────────────────

    /// <summary>
    /// Relative path where the Palma web API exposes its MCP endpoint list.
    /// The Palma API must implement: GET {ApiBaseUrl}{EndpointsPath}
    ///   → returns IEnumerable&lt;PalmaEndpointInfo&gt; as JSON.
    /// Default: "/api/mcp/endpoints"
    /// </summary>
    public string EndpointsPath { get; init; } = "/api/mcp/endpoints";

    /// <summary>
    /// Query parameter names that carry per-session Palma context.
    /// Stripped from tool InputSchemas; injected by <see cref="PalmaRemoteToolInvoker"/>.
    /// </summary>
    public string[] ContextQueryParams { get; init; } = ["org", "ms", "branch"];
}
